easy_admin:
    entities:
#        # List the entity class name you want to manage
        - App\Entity\TripMgr\Destination
        - App\Entity\TripMgr\Landmark
        - App\Entity\TripMgr\Trip
        - App\Entity\UserMgr\Customer
        - App\Entity\UserMgr\Offer
        - App\Entity\UserMgr\User
